const blacklist = [
  // --- ESPAÑOL (Ampliación muy extensa) ---
  "puta",
  "muerete",
  "muérete",
  "ojala te mueras",
  "ojalá te mueras",
  "ojala mueras",
  "te mueras",
  "revienta",
  "revientate",
  "palma",
  "que te mueras",
  "deseo que mueras",
  "muerto seas",
  "ojala revientes",
  "te pudras",
  "te mueras pronto",
  "onlyfans",
  "only fans",
  "mi onlyfans",
  "suscríbete a mi only",
  "pack onlyfans",
  "my onlyfans",
  "enlace onlyfans",
  "nudes onlyfans",
  "contenido adulto",
  "puto",
  "puton",
  "putón",
  "canceroso",
  "muérete",
  "muerete",
  "sidoso",
  "hdp",
  "hijo de puta",
  "hija de puta",
  "hijueputa",
  "hijueputas",
  "maricon",
  "maricón",
  "marica",
  "maricón de mierda",
  "bollera",
  "travelo",
  "tranny",
  "maricazo",
  "gilipollas",
  "gilipollas de mierda",
  "gilipollín",
  "pollas",
  "etarra",
  "etarras",
  "poya",
  "polla",
  "polla gorda",
  "coño",
  "cojon",
  "cojón",
  "cojones",
  "cojones colgando",
  "huevos colgando",
  "cabron",
  "cabrón",
  "cabrona",
  "cabrón de mierda",
  "pendejo",
  "pendeja",
  "pendejo de mierda",
  "boludo",
  "pelotudo",
  "pelotudo de mierda",
  "imbecil",
  "imbécil",
  "imbécil mental",
  "idiota",
  "estupido",
  "estúpido",
  "estupida",
  "estúpida",
  "estúpido de remate",
  "subnormal",
  "subnormal de mierda",
  "retrasado",
  "retrasado mental",
  "mongolo",
  "mongolico",
  "mongólico",
  "down",
  "down de mierda",
  "basura",
  "escoria",
  "mierda",
  "cagar",
  "joder",
  "jodete",
  "jódete",
  "jodido",
  "me cago en",
  "me cago en tu puta madre",
  "facha",
  "nazi",
  "comunista de mierda",
  "perroflauta",
  "progre de mierda",
  "moro",
  "sudaca",
  "panchito",
  "guiri",
  "negro de mierda",
  "machupichu",
  "gitano de mierda",
  "catalan de mierda",
  "españolazo",
  "fajilla",
  "facha de mierda",
  "caraculo",
  "asqueroso",
  "pajillero",
  "malnacido",
  "mamon",
  "mamón",
  "mamón de mierda",
  "lerdo",
  "cenutrio",
  "zoquete",
  "abanto",
  "alcornoque",
  "alfeñique",
  "baboso",
  "bellaco",
  "berzotas",
  "besugo",
  "bobalicón",
  "borinot",
  "borracho",
  "bocachancla",
  "capullo",
  "capullo integral",
  "carajaula",
  "cuerpoescombro",
  "gaznápiro",
  "huevon",
  "huevón",
  "huevón de mierda",
  "inútil",
  "lerdo",
  "majadero",
  "malaje",
  "mastuerzo",
  "mentecato",
  "niñato",
  "pajillero",
  "pasmado",
  "payaso",
  "piltrafilla",
  "pintamonas",
  "soplagaitas",
  "tonto",
  "tonto del culo",
  "tonto del haba",
  "zampabollos",
  "zopenco",
  "zote",
  "parguela",
  "pringao",
  "parguelon",
  "parguelón",
  "panoli",
  "tuercebotas",
  "pagafantas",
  "melafo",
  "follatelo",
  "follatela",
  "calientabragas",
  "comepollas",
  "tragaleches",
  "chupapollas",
  "chupatintas",
  "lameculos",
  "lametraserillos",
  "bienqueda",
  "facha de mierda",
  "rojo de mierda",
  "perro sanxe",
  "mugroso",
  "cayetano",
  "rata",
  "gentuza",
  "chusma",
  "pobreton",
  "pobretón",
  "muerto de hambre",
  "apestoso",
  "sarnoso",
  "sarnosa",
  "hijo de mil putas",
  "hijo de una perra",
  "malparida",
  "cornudo",
  "ciervo",
  "venao",
  "cornuda",
  "zorron",
  "zorrón",
  "zorra",
  "guarra",
  "guarron",
  "guarrón",
  "cerdo",
  "puerca",
  "marranada",
  "marrano",
  "pitufo",
  "picoleto",
  "madero",
  "pasma",
  "estos catalanes",
  "estos españoles",
  "hijoputa",
  "hijoputísima",
  "hijadeputa",
  "mamahuevo",
  "mamaguevo",
  "mamahuevos",
  "chupamedias",
  "chupapollas",
  "chupapitos",
  "lambeculos",
  "lambebotas",
  "lamberetas",
  "culero",
  "culera",
  "culiao",
  "culión",
  "culicagado",
  "culicagado de mierda",
  "pinche",
  "pinche puto",
  "pinche cabrón",
  "pinche pendejo",
  "pinche wey",
  "güey de mierda",
  "pendejo culero",
  "verga",
  "vergas",
  "verga de mierda",
  "chingada",
  "chingadera",
  "chingón",
  "chingaquedito",
  "me cago en la leche",
  "me cago en la mar",
  "me cago en tus muertos",
  "hostia puta",
  "la hostia",
  "ostia",
  "ostias",
  "la hostia en vinagre",
  "me cago en la hostia",
  "zorra",
  "zorrón",
  "zorra asquerosa",
  "puticlub",
  "putero",
  "puticlubera",
  "follacabras",
  "follaovejas",
  "follahermanas",
  "incesto",
  "degenerado",
  "degenerada",
  "pervertido",
  "cerdo asqueroso",
  "guarro",
  "guarra de mierda",
  "cerda",
  "cerdito",
  "baboso",
  "babosa",
  "babosada",
  "mojado",
  "mojada",
  "mojigato",
  "mojigata",
  "pringado",
  "pringao",
  "pringadillo",
  "pringuetón",
  "pringón",
  "pringoso",
  "cateto",
  "paleto",
  "palurdo",
  "paleto de mierda",
  "redneck",
  "pueblerino",
  "choni",
  "chulita",
  "choni de barrio",
  "poligonera",
  "poligonero",
  "choni total",
  "canalla",
  "granuja",
  "sinvergüenza",
  "sinvergüenza de mierda",
  "bribón",
  "pícaro",
  "pícaro de mierda",
  "truhán",
  "timador",
  "estafador de pacotilla",
  "mangante",
  "manganta",
  "ratero",
  "ratera",
  "ladrón",
  "ladrona",
  "chorizo",
  "choriza",
  "raterillo",
  "ratería",
  "caco",
  "caco de mierda",
  "cobarde",
  "gallina",
  "cagueta",
  "cagado",
  "cagón",
  "cagaprisas",
  "cagafuegos",
  "pusilánime",
  "miedica",
  "miedoso",
  "maricón cobarde",
  "marica cagado",
  "flojeras",
  "vago",
  "vagabundo",
  "holgazán",
  "vago de mierda",
  "gandul",
  "gandula",
  "haragán",
  "zángano",
  "zángana",
  "zángano de mierda",
  "parásito",
  "parásita",
  "chupóptero",
  "chupasangre",
  "sanguijuela",
  "aprovechado",
  "aprovechada",
  "caradura",
  "caradura de mierda",
  "caradura sinvergüenza",
  "descarado",
  "descarada",
  "fresco",
  "fresca",
  "listillo",
  "listilla",
  "sabelotodo",
  "sabelotodo de mierda",
  "setciències",
  "sabelotodo repelente",
  "sabelotodo insoportable",
  "facha",
  "fachoso",
  "fachenda",
  "facha de mierda",
  "facha rancia",
  "fachaprogre",
  "facha progre",
  "facha de izquierdas",
  "facha de derechas",
  "rojo",
  "rojo de mierda",
  "rojo malayo",
  "rojo comunista",
  "rojo hijoputa",
  "perroflauta",
  "perroflauta de mierda",
  "okupa",
  "okupa de mierda",
  "indignado",
  "indignado de pacotilla",
  "progre",
  "progre de mierda",
  "progre buenista",
  "buenista",
  "buenrollista",
  "buenrollista de mierda",
  "moñas",
  "moñas de mierda",
  "sensiblero",
  "sensiblera",
  "llorón",
  "llorona",
  "lloricas",
  "plañidero",
  "plañidera",
  "victimista",
  "victimista de mierda",
  "snowflake",
  "nieve de mierda",
  "frágil",
  "frágil mental",
  "frágil de cojones",

  // --- CATALÁN (Ampliación) ---
  "collons",
  "collonut",
  "cony",
  "merda",
  "fill de puta",
  "filla de puta",
  "fill de la gran puta",
  "maldit",
  "malparit",
  "capsigrany",
  "burro",
  "estúpid",
  "imbècil",
  "imbècil de merda",
  "poca-solta",
  "meco",
  "palleter",
  "bagassa",
  "desgraciat",
  "figa",
  "pixapins",
  "bandoler",
  "tros d'ase",
  "ximple",
  "babau",
  "carallot",
  "estaquirot",
  "galifardeu",
  "llepaculs",
  "mitja merda",
  "napbuf",
  "panxacontenta",
  "tanoca",
  "tros de quòniam",
  "cap de fava",
  "cul de mal se t'hi vegi",
  "fava tendra",
  "llagosta",
  "merda seca",
  "oca",
  "soca",
  "carnús",
  "pixandurri",
  "estalentat",
  "ruc",
  "ruc de fava",
  "paparra",
  "tabalot",
  "cap de suro",
  "txitxarel·lo",
  "malnascut",
  "pixaví",
  "escurçó",
  "pendó",
  "lladre",
  "estafador",
  "botifler",
  "nyordo",
  "carallot",
  "tros de quòniam",
  "tros d'ase",
  "tros de quòniam d'ase",
  "gamarús",
  "betzol",
  "betzo",
  "soca",
  "ximple",
  "ximplota",
  "ximplote",
  "bleda assolellada",
  "figaflor",
  "figa-seca",
  "fava tendra",
  "fava",
  "cap de suro",
  "cap de fava",
  "cap de cony",
  "cap de morros de cony",
  "capsigrany",
  "estaquirot",
  "talòs",
  "talala",
  "tòtil",
  "tòtila",
  "tanoca",
  "tanoca de merda",
  "borinot",
  "borinot xerraire",
  "pixapins",
  "pixafreda",
  "titafreda",
  "titella",
  "titella de merda",
  "torracollons",
  "torrapebrots",
  "torracastanyes",
  "torracollons de merda",
  "abarrotat",
  "abarrotada",
  "abarrotat de merda",
  "xarnego",
  "xarnego de merda",
  "botifler",
  "botifler de merda",
  "nyordo",
  "nyord de merda",
  "tabalot",
  "tabalot de merda",
  "merda-seca",
  "toca-son",
  "abellot",
  "baboia",
  "eixorc",
  "pet bufat",
  "lladre",
  "escurçó",
  "pendó",

  // --- EUSKERA (Basque – Ampliación) ---
  "ferreki",
  "arraiua",
  "kaka",
  "kaka zaharra",
  "alua",
  "putaseme",
  "tinoiputz",
  "tentela",
  "txatxu",
  "zozoa",
  "ergela",
  "astakilo",
  "guiri kaka",
  "maketo",
  "txakur",
  "txoriburu",
  "tontolapiko",
  "ganorabako",
  "potrohandi",
  "artaburu",
  "babó",
  "kaiku",
  "txakur txiki",
  "txorito",
  "ergel",
  "astakeria",
  "buru txiki",
  "burugabe",
  "mamarro",
  "pikutara",
  "pikutara joan",
  "atzo goizekoa",
  "guiri simaurra",
  "txatxala",
  "inozoa",
  "kaskagandila",
  "kakati",
  "mandul",
  "mukizu",
  "txoriburu",
  "tontolapiko",
  "ganorabako",
  "potrohandi",
  "artaburu",
  "kaskagandila",
  "kakati",
  "mandul",
  "mukizu",
  "pikutara",
  "pikutara joan",
  "txatxala",
  "inozoa",
  "astakeria",
  "burugabe",
  "mamarro",
  "txakur txiki",
  "txorito",
  "ergel",
  "buru txiki",
  "kaiku",
  "babó",
  "guiri simaurra",
  "alua",
  "putaseme",
  "tinoiputz",
  "tentela",
  "txatxu",
  "zozoa",

  // --- GALEGO (Galician – Ampliación) ---
  "carallo",
  "filla da puta",
  "fillo da puta",
  "merda",
  "pailán",
  "haxa",
  "parvo",
  "paspallás",
  "fodas",
  "conas",
  "pailan",
  "ghicho de merda",
  "babeco",
  "langrán",
  "tolleito",
  "baldreu",
  "barallocas",
  "bulebule",
  "camándula",
  "chaíñas",
  "chocalleiro",
  "fodechinchos",
  "lercha",
  "moinante",
  "lambefigos",
  "zalapastrán",
  "tarambaina",
  "baboso",
  "parvo/a",
  "babeco/a",
  "fervellasverzas",
  "lambecricas",
  "cara de cona",
  "sopla pollás",
  "animal de bellota",
  "becho",
  "bouzas",
  "carallán",
  "cazurro",
  "chuchamel",
  "furela",
  "ghicho",
  "mexacán",
  "miñaxoia",
  "paiaso",
  "pasmón",
  "reghitón",
  "tolo",
  "tripallán",
  "vacaloura",
  "carallán",
  "tolleito",
  "tripallán",
  "vacaloura",
  "paiaso",
  "pasmón",
  "reghitón",
  "tolo",
  "fervellasverzas",
  "lambecricas",
  "zalapastrán",
  "tarambaina",
  "chuchamel",
  "furela",
  "ghicho",
  "mexacán",
  "miñaxoia",
  "animal de bellota",
  "becho",
  "bouzas",
  "cazurro",
  "langrán",
  "babeco",
  "parvo",
  "parva",
  "parvo/a de merda",
  "pailán",
  "pailan de merda",

  // --- INGLÉS (Ampliación) ---
  "fuck",
  "fucker",
  "fucking",
  "motherfucker",
  "mf",
  "stfu",
  "wanker",
  "shit",
  "shitty",
  "bullshit",
  "piece of shit",
  "crap",
  "bitch",
  "bastard",
  "asshole",
  "dick",
  "pussy",
  "cunt",
  "twat",
  "gay",
  "faggot",
  "dyke",
  "nigger",
  "nigga",
  "retard",
  "spic",
  "idiot",
  "stupid",
  "dumb",
  "dumbass",
  "loser",
  "scum",
  "prick",
  "cock",
  "douche",
  "douchebag",
  "jackass",
  "moron",
  "dipshit",
  "fuckwit",
  "twatface",
  "incel",
  "simp",
  "cuck",
  "cuckold",
  "thot",
  "whore",
  "slut",
  "skank",
  "snowflake",
  "libtard",
  "magat",
  "commie",
  "nazi scum",
  "terf",
  "fuckface",
  "shithead",
  "dickhead",
  "dumbfuck",
  "assclown",
  "twatwaffle",
  "shat",
  "shitter",
  "wankstain",
  "cockhead",
  "cock sucker",
  "suck it",
  "suck my dick",
  "suck my balls",
  "suck my ass",
  "suck my pussy",
  "suck my clit",
  "suck my balls",
  "suck my ass",
  "suck my pussy",
  "suck my clit",
  "cocksucker",
  "son of a bitch",
  "son of a whore",
  "son of a gun",
  "bitch ass",
  "punk ass",
  "punk",
  "fucking idiot",
  "fucking bitch",
  "dumb bitch",
  "fat fuck",
  "ugly fuck",
  "creepy fuck",
  "weirdo",
  "freak",
  "numbnuts",
  "numbskull",
  "peckerwood",
  "redneck",
  "hillbilly",
  "white trash",
  "trailer trash",
  "ghetto",
  "hoodrat",
  "ratchet",
  "bimbos",
  "bimbo",
  "himbo",
  "chad",
  "karen",
  "boomer",
  "zoomer",
  "doomer",
  "gloomer",
  "bloomer",
  "coomer",
  "consoomer",
  "normie",
  "pleb",
  "peasant",
  "loser",
  "failure",
  "disappointment",
  "mistake",
  "accident",
  "worthless",
  "useless",
  "pathetic",
  "sad",
  "miserable",
  "depressing",
  "annoying",
  "irritating",
  "frustrating",
  "infuriating",
  "disgusting",
  "gross",
  "nasty",
  "vile",
  "repulsive",
  "revolting",
  "sickening",
  "nauseating",
  "horrible",
  "terrible",
  "awful",
  "dreadful",
  "appalling",
  "atrocious",
  "abominable",
  "monstrous",

  // --- FRANCÉS (Ampliación) ---
  "merde",
  "putain",
  "connard",
  "connasse",
  "salope",
  "fils de pute",
  "enculé",
  "abruti",
  "débile",
  "bordel",
  "chiant",
  "con",
  "conne",
  "enculeur",
  "batard",
  "pute",
  "nique ta mère",
  "va te faire foutre",
  "trou du cul",
  "branleur",
  "pede",
  "sale juif",
  "sale arabe",
  "nique ta grand-mère",
  "nique ta race",
  "ta gueule",
  "ferme ta gueule",
  "casse-toi",
  "va chier",
  "poufiasse",
  "gouine",
  "pédale",
  "tapette",
  "tarlouze",
  "fiotte",
  "macaque",
  "nègre",
  "bougnoule",
  "bicot",
  "raton",
  "niakoué",
  "chinetoque",
  "bolosse",
  "kéké",
  "cagole",
  "beauf",
  "gros porc",
  "grosse vache",
  "bâtard de merde",
  "sac à merde",
  "tête de nœud",
  "tête de con",
  "face de pet",
  "mange-merde",
  "suce-bite",
  "clochard",
  "crevard",
  "radin",
  "rat",
  "pigeon",
  "mouton",
  "vendu",
  "collabo",
  "traître",
  "lâche",
  "pleutre",
  "poltron",
  "couard",
  "froussard",
  "dégonflé",
  "mauviette",
  "mollasson",

  // --- ITALIANO (Ampliación) ---
  "cazzo",
  "vaffanculo",
  "stronzo",
  "stronza",
  "puttana",
  "merda",
  "finocchio",
  "troia",
  "bastardo",
  "coglione",
  "minchia",
  "rompicoglioni",
  "testa di cazzo",
  "fanculo",
  "porca troia",
  "vaffanculo a te e alla tua famiglia",
  "coglioni",
  "figlio di puttana",
  "porca miseria",
  "porca madonna",
  "dio cane",
  "dio porco",
  "mannaggia",
  "li mortacci tua",
  "testa di minchia",
  "faccia di cazzo",
  "rottinculo",
  "succhiacazzi",
  "leccaculo",
  "cornuto",
  "bagascia",
  "zoccola",
  "mignotta",
  "baldracca",
  "scrofa",
  "maiala",
  "vacca",
  "frocio",
  "ricchione",
  "culattone",
  "mezzo omo",
  "terrone",
  "polentone",
  "marocchino di merda",
  "zingaro di merda",
  "negro di merda",
  "ebreo di merda",
  "cinese di merda",
  "idiota",
  "imbecille",
  "deficiente",
  "ritardato",
  "handicappato",
  "mongoloide",
  "spastico",
  "scemo",
  "cretino",
  "stupido",
  "ignorante",
  "asino",
  "capra",
  "bestia",
  "animale",
  "bastardo pezzo di merda",
  "figlio di troia",
  "figlio di mignotta",
  "figlio di baldracca",

  // --- PORTUGUÉS (Ampliación) ---
  "porra",
  "caralho",
  "puta que pariu",
  "merda",
  "foda-se",
  "filho da puta",
  "corno",
  "paneleiro",
  "rapariga",
  "puta",
  "vai tomar no cu",
  "bicha",
  "viado",
  "arrombado",
  "escroto",
  "otário",
  "babaca",
  "cabrão",
  "filha da puta",
  "cabrões",
  "putedo",
  "vai dar a curva",
  "vai levar no pacote",
  "vai à merda",
  "vai-te foder",
  "foder",
  "foda",
  "fodilhoca",
  "conos",
  "cona",
  "paneleirice",
  "maricas",
  "paneleirinho",
  "rabeta",
  "rabetolas",
  "panasca",
  "sapatão",
  "febra",
  "fufa",
  "cabra",
  "vaca",
  "porca",
  "galdéria",
  "badalhoca",
  "nojo",
  "nojeira",
  "escrotidão",
  "palerma",
  "panhonhas",
  "parvalhão",
  "parvo",
  "idiota",
  "imbecil",
  "estúpido",
  "burro",
  "besta",
  "calhau",
  "nabo",
  "tanso",
  "sacana",
  "pulha",
  "canalha",
  "bandido",
  "ladrão",
  "gatuno",
  "corrupto",
  "chulo",
  "chulado",
  "malandro",
  "vagabundo",
  "parasita",
  "sugador",
  "sanguessuga",

  // --- ALEMÁN (Ampliación) ---
  "scheisse",
  "heil hitler",
  "arschloch",
  "schlampe",
  "fick dich",
  "wichser",
  "hurensohn",
  "mist",
  "depp",
  "verdammt",
  "fotze",
  "arsch",
  "dummkopf",
  "idiot",
  "schwachkopf",
  "drecksau",
  "lutscher",
  "spast",
  "nazi schweine",
  "pisskopf",
  "pissgesicht",
  "kackbombe",
  "scheißkerl",
  "scheißhaus",
  "hure",
  "nutte",
  "bitch",
  "fotzenknecht",
  "schwuchtel",
  "transe",
  "homo",
  "kanake",
  "bimbo",
  "neger",
  "judenschwein",
  "assozialer",
  "assi",
  "penner",
  "obdachloser",
  "junkie",
  "stricher",
  "strichjunge",
  "strichmädchen",
  "strichnutte",
  "strichhure",
  "strichschlampe",
  "dämlack",
  "vollpfosten",
  "honk",
  "horst",
  "lauch",
  "oberlauch",
  "opfer",
  "lappen",
  "kek",
  "cuck",
  "simp",
  "incel",
  "alpha",
  "beta",
  "sigma",
  "giga chad",
  "bastard",
  "hundesohn",
  "drecksfink",
  "schweinepriester",
  "miststück",
  "dreckschleuder",
  "blödmann",
  "blödkuh",
  "ziege",
  "alte schachtel",
  "alte hexe",
  "drache",
  "monster",
];
export { blacklist };
