const blacklist = [
  // --- ESPAÑOL ---
  "puta",
  "muerete",
  "muérete",
  "ojala te mueras",
  "ojalá te mueras",
  "ojala mueras",
  "te mueras",
  "revienta",
  "revientate",
  "ojala revientes",
  "te pudras",
  "te mueras pronto",
  "onlyfans",
  "only fans",
  "mi onlyfans",
  "suscríbete a mi only",
  "pack onlyfans",
  "my onlyfans",
  "enlace onlyfans",
  "nudes onlyfans",
  "contenido adulto",
  "puto",
  "puton",
  "putón",
  "canceroso",
  "sidoso",
  "hdp",
  "hijo de puta",
  "hija de puta",
  "hijueputa",
  "hijueputas",
  "maricon",
  "maricón",
  "maricazo",
  "gilipollas",
  "gilipollín",
  "pollas",
  "etarra",
  "etarras",
  "poya",
  "polla",
  "coño",
  "cojon",
  "cojón",
  "cojones",
  "cabron",
  "cabrón",
  "cabrona",
  "pendejo",
  "pendeja",
  "boludo",
  "pelotudo",
  "imbecil",
  "imbécil",
  "idiota",
  "estupido",
  "estúpido",
  "estupida",
  "estúpida",
  "subnormal",
  "retrasado",
  "retrasado mental",
  "mongolo",
  "mongolico",
  "mongólico",
  "mierda",
  "jodete",
  "jódete",
  "me cago en tu puta madre",
  "nazi",
  "moro",
  "sudaca",
  "negro de mierda",
  "gitano de mierda",
  "caraculo",
  "asqueroso",
  "pajillero",
  "malnacido",
  "mamon",
  "mamón",
  "inútil",
  "majadero",
  "comepollas",
  "tragaleches",
  "chupapollas",
  "lameculos",
  "mugroso",
  "gentuza",
  "chusma",
  "apestoso",
  "sarnoso",
  "sarnosa",
  "hijo de mil putas",
  "hijo de una perra",
  "malparida",
  "cornudo",
  "cornuda",
  "zorra",
  "guarra",
  "cerdo",
  "puerca",
  "marranada",
  "marrano",
  "hijoputa",
  "hijoputísima",
  "hijadeputa",
  "mamahuevo",
  "mamaguevo",
  "chupamedias",
  "chupapitos",
  "lambeculos",
  "culero",
  "culicagado",
  "pinche puto",
  "pinche cabrón",
  "pinche pendejo",
  "verga",
  "chingada",
  "me cago en la leche",
  "me cago en tus muertos",
  "hostia puta",
  "zorra asquerosa",
  "puticlub",
  "putero",
  "follacabras",
  "follaovejas",
  "incesto",
  "degenerado",
  "degenerada",
  "pervertido",
  "cerdo asqueroso",
  "guarro",
  "pringado",
  "pringao",

  // --- CATALÁN ---
  "collons",
  "cony",
  "merda",
  "fill de puta",
  "filla de puta",
  "fill de la gran puta",
  "maldit",
  "malparit",
  "capsigrany",
  "imbècil",
  "bagassa",
  "desgraciat",
  "llepaculs",
  "carallot",
  "malnascut",
  "xarnego",
  "botifler",
  "tros d'ase",
  "cap de fava",
  "cap de cony",

  // --- EUSKERA ---
  "alua",
  "putaseme",
  "tinoiputz",
  "maketo",
  "txakur",
  "guiri kaka",
  "astakilo",
  "burugabe",

  // --- GALEGO ---
  "carallo",
  "filla da puta",
  "fillo da puta",
  "fodas",
  "conas",
  "ghicho de merda",

  // --- INGLÉS ---
  "fuck",
  "fucker",
  "fucking",
  "motherfucker",
  "wanker",
  "shit",
  "bullshit",
  "piece of shit",
  "bitch",
  "bastard",
  "asshole",
  "dick",
  "cunt",
  "twat",
  "faggot",
  "dyke",
  "nigger",
  "nigga",
  "retard",
  "spic",
  "dumbass",
  "scum",
  "prick",
  "cock",
  "douchebag",
  "jackass",
  "moron",
  "dipshit",
  "fuckwit",
  "fuckface",
  "shithead",
  "dickhead",
  "dumbfuck",
  "cocksucker",
  "son of a bitch",
  "son of a whore",
  "fucking idiot",
  "fucking bitch",
  "suck my dick",
  "suck my balls",
  "go kill yourself",
  "kys",
  "white trash",
  "libtard",
  "nazi scum",

  // --- FRANCÉS ---
  "merde",
  "putain",
  "connard",
  "connasse",
  "salope",
  "fils de pute",
  "enculé",
  "abruti",
  "enculeur",
  "batard",
  "pute",
  "nique ta mère",
  "va te faire foutre",
  "branleur",
  "sale juif",
  "sale arabe",
  "nique ta race",
  "ta gueule",
  "va chier",
  "poufiasse",
  "gouine",
  "pédale",
  "tarlouze",
  "macaque",
  "nègre",
  "bougnoule",
  "bicot",
  "chinetoque",
  "gros porc",
  "bâtard de merde",
  "suce-bite",
  "mange-merde",

  // --- ITALIANO ---
  "cazzo",
  "vaffanculo",
  "stronzo",
  "stronza",
  "puttana",
  "finocchio",
  "troia",
  "coglione",
  "minchia",
  "testa di cazzo",
  "porca troia",
  "figlio di puttana",
  "li mortacci tua",
  "succhiacazzi",
  "leccaculo",
  "cornuto",
  "zoccola",
  "mignotta",
  "frocio",
  "ricchione",
  "terrone",
  "marocchino di merda",
  "zingaro di merda",
  "negro di merda",
  "ritardato",
  "mongoloide",
  "bastardo pezzo di merda",

  // --- PORTUGUÉS ---
  "porra",
  "caralho",
  "puta que pariu",
  "foda-se",
  "filho da puta",
  "paneleiro",
  "vai tomar no cu",
  "arrombado",
  "escroto",
  "cabrão",
  "filha da puta",
  "vai à merda",
  "vai-te foder",
  "parvalhão",
  "sacana",
  "canalha",
  "ladrão",
  "corrupto",

  // --- ALEMÁN ---
  "scheisse",
  "heil hitler",
  "arschloch",
  "schlampe",
  "fick dich",
  "wichser",
  "hurensohn",
  "fotze",
  "drecksau",
  "nazi schweine",
  "scheißkerl",
  "hure",
  "nutte",
  "fotzenknecht",
  "schwuchtel",
  "kanake",
  "judenschwein",
  "hundesohn",
  "schweinepriester",
  "blödmann",
];

export { blacklist };
